defaults: &defaults
  url: "https://slack6386.zendesk.com/api/v2/"
  key: 'Basic cmV1YmVuLnJhamVldkBnbWFpbC5jb206dGVzdGluZw=='
  content_type: "application/json"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults